=== alanrodas/Fronttier/dtd/xml.dtd
<!ELEMENT fronttier (repositories?, dependencies)>
<!ELEMENT repositories (repository*)>
<!ELEMENT repository (type?, url)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT dependencies (dependency*)>
<!ELEMENT dependency (group, name, version?)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT version (#PCDATA)>

=== alanrodas/Fronttier/fronttier.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fronttier PUBLIC "-/Fronttier/xml.dtd" "http://fronttier.alanrodas.com/dtd/xml.dtd">
<fronttier>
    <repositories>
        <repository>
            <type>git</type>
            <url>http://myrepository.com</url>
        </repository>
        <repository>
            <url>https://some-other-repo.org/repository</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <group>org.jquery</group>
            <name>jquery</name>
            <version>2.11.0</version>
        </dependency>
        <dependency>
            <group>org.jquery</group>
            <name>jquery-ui</name>
        </dependency>
    </dependencies>
</fronttier>
